# Generated by Django 3.2.3 on 2021-05-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/media/'),
        ),
    ]
